"""
Solution 2: Custom Streamer for Token-by-Token Streaming

This solution creates a custom TextStreamer that captures tokens in a queue
instead of printing to console. This allows you to stream tokens to clients
in real-time.

Pros:
- True token-by-token streaming
- Works with existing HuggingFace model
- Can integrate with web frameworks

Cons:
- Requires monkey-patching or model code modification
- More complex implementation
"""

from transformers import AutoModel, AutoTokenizer, TextStreamer
import torch
import os
from queue import Queue
from threading import Thread
import time

# Configuration
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
model_name = 'deepseek-ai/DeepSeek-OCR'


class CustomTokenStreamer(TextStreamer):
    """
    Custom streamer that captures tokens in a queue instead of printing.
    This allows streaming tokens to clients in real-time.
    """
    
    def __init__(self, tokenizer, skip_prompt=True, skip_special_tokens=False, callback=None):
        super().__init__(tokenizer, skip_prompt=skip_prompt, skip_special_tokens=skip_special_tokens)
        self.token_queue = Queue()
        self.callback = callback
        self.finished = False
        
    def on_finalized_text(self, text: str, stream_end: bool = False):
        """Called when a piece of text is finalized and ready to be displayed."""
        # Clean up EOS tokens like the original NoEOSTextStreamer
        eos_text = self.tokenizer.decode([self.tokenizer.eos_token_id], skip_special_tokens=False)
        text = text.replace(eos_text, "\n")
        
        # Put text in queue for consumption
        self.token_queue.put(text)
        
        # Call callback if provided (for real-time processing)
        if self.callback:
            self.callback(text)
        
        # Signal end of stream
        if stream_end:
            self.token_queue.put(None)  # Sentinel value
            self.finished = True
    
    def get_tokens(self):
        """Generator that yields tokens as they become available."""
        while True:
            token = self.token_queue.get()
            if token is None:  # End of stream
                break
            yield token


def infer_with_streaming(model, tokenizer, prompt, image_file, output_path='output', 
                        base_size=1024, image_size=640, crop_mode=True, callback=None):
    """
    Modified infer function that returns a generator for streaming tokens.
    
    Args:
        model: The DeepSeek-OCR model
        tokenizer: The tokenizer
        prompt: Text prompt
        image_file: Path to image file
        output_path: Output directory
        base_size: Base resolution
        image_size: Patch resolution
        crop_mode: Whether to use dynamic cropping
        callback: Optional callback function called for each token
    
    Returns:
        Generator that yields tokens as they are generated
    """
    
    # Create custom streamer
    streamer = CustomTokenStreamer(
        tokenizer, 
        skip_prompt=True, 
        skip_special_tokens=False,
        callback=callback
    )
    
    # Start generation in a separate thread
    def generate():
        # Note: This is a simplified version. The actual implementation would need
        # to replicate the full logic from the model's infer() method including
        # image preprocessing, etc.
        
        # For demonstration, we'll call the model's infer with a monkey-patched streamer
        # In practice, you'd need to either:
        # 1. Modify the model code directly
        # 2. Copy the infer logic and use your custom streamer
        # 3. Use the vLLM implementation (Solution 3)
        
        print("Note: This is a demonstration. Full implementation requires modifying model code.")
        print("For production use, consider Solution 3 (vLLM) which has native streaming support.")
        
        # Simulate streaming for demonstration
        demo_text = "This is a demonstration of token streaming. "
        demo_text += "In the actual implementation, this would be the model's output. "
        demo_text += "Each chunk would be generated by the model in real-time."
        
        for chunk in demo_text.split():
            time.sleep(0.1)  # Simulate generation delay
            streamer.on_finalized_text(chunk + " ", stream_end=False)
        
        streamer.on_finalized_text("", stream_end=True)
    
    # Start generation thread
    thread = Thread(target=generate)
    thread.start()
    
    # Return generator
    return streamer.get_tokens()


# Example 1: Simple streaming to console
def example_console_streaming():
    """Example: Stream tokens to console with custom formatting."""
    print("=" * 80)
    print("Example 1: Console Streaming")
    print("=" * 80)
    
    # Load model (commented out for demo)
    # tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    # model = AutoModel.from_pretrained(model_name, trust_remote_code=True)
    # model = model.eval().cuda().to(torch.bfloat16)
    
    # For demo purposes, we'll use None
    model = None
    tokenizer = None
    
    prompt = "<image>\n<|grounding|>Convert the document to markdown."
    image_file = 'your_image.jpg'
    
    print(f"\nStreaming output:\n")
    
    full_text = ""
    for token in infer_with_streaming(model, tokenizer, prompt, image_file):
        print(token, end='', flush=True)
        full_text += token
    
    print(f"\n\nTotal length: {len(full_text)} characters")


# Example 2: Streaming to a web client (Flask with SSE)
def example_flask_sse():
    """Example: Flask server with Server-Sent Events for streaming."""
    
    code = '''
from flask import Flask, Response, request
import json

app = Flask(__name__)

# Load model once at startup
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModel.from_pretrained(model_name, trust_remote_code=True)
model = model.eval().cuda().to(torch.bfloat16)

@app.route('/ocr/stream', methods=['POST'])
def ocr_stream():
    """Endpoint that streams OCR results using Server-Sent Events."""
    data = request.json
    image_path = data.get('image_path')
    prompt = data.get('prompt', '<image>\\nFree OCR.')
    
    def generate():
        """Generator function for SSE."""
        try:
            # Stream tokens as they're generated
            for token in infer_with_streaming(model, tokenizer, prompt, image_path):
                # Format as SSE
                yield f"data: {json.dumps({'token': token})}\\n\\n"
            
            # Send completion signal
            yield f"data: {json.dumps({'done': True})}\\n\\n"
            
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\\n\\n"
    
    return Response(generate(), mimetype='text/event-stream')

@app.route('/ocr', methods=['POST'])
def ocr_full():
    """Endpoint that returns full result (non-streaming)."""
    data = request.json
    image_path = data.get('image_path')
    prompt = data.get('prompt', '<image>\\nFree OCR.')
    
    # Collect all tokens
    full_text = ""
    for token in infer_with_streaming(model, tokenizer, prompt, image_path):
        full_text += token
    
    return {'success': True, 'text': full_text}

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
'''
    
    print("=" * 80)
    print("Example 2: Flask with Server-Sent Events")
    print("=" * 80)
    print(code)


# Example 3: Streaming with callback for real-time processing
def example_callback_processing():
    """Example: Use callback for real-time processing of tokens."""
    print("=" * 80)
    print("Example 3: Callback Processing")
    print("=" * 80)
    
    collected_tokens = []
    
    def token_callback(token):
        """Called for each token as it's generated."""
        collected_tokens.append(token)
        
        # Example: Send to websocket
        # websocket.send(json.dumps({'token': token}))
        
        # Example: Update database
        # db.update_progress(session_id, token)
        
        # Example: Log to file
        # logger.info(f"Generated token: {token}")
        
        print(f"[CALLBACK] Received token: {repr(token)}")
    
    model = None
    tokenizer = None
    prompt = "<image>\n<|grounding|>Convert the document to markdown."
    image_file = 'your_image.jpg'
    
    print("\nStreaming with callback:\n")
    
    # Stream with callback
    for token in infer_with_streaming(model, tokenizer, prompt, image_file, callback=token_callback):
        pass  # Callback handles each token
    
    print(f"\n\nCollected {len(collected_tokens)} tokens")
    print(f"Full text: {''.join(collected_tokens)}")


# Example 4: WebSocket streaming
def example_websocket():
    """Example: WebSocket server for real-time streaming."""
    
    code = '''
from fastapi import FastAPI, WebSocket
from fastapi.responses import HTMLResponse
import json

app = FastAPI()

# Load model once at startup
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModel.from_pretrained(model_name, trust_remote_code=True)
model = model.eval().cuda().to(torch.bfloat16)

@app.websocket("/ws/ocr")
async def websocket_ocr(websocket: WebSocket):
    """WebSocket endpoint for streaming OCR results."""
    await websocket.accept()
    
    try:
        # Receive request
        data = await websocket.receive_json()
        image_path = data.get('image_path')
        prompt = data.get('prompt', '<image>\\nFree OCR.')
        
        # Send status
        await websocket.send_json({'status': 'processing'})
        
        # Stream tokens
        for token in infer_with_streaming(model, tokenizer, prompt, image_path):
            await websocket.send_json({'token': token})
        
        # Send completion
        await websocket.send_json({'status': 'complete'})
        
    except Exception as e:
        await websocket.send_json({'error': str(e)})
    finally:
        await websocket.close()

# HTML client for testing
@app.get("/")
async def get():
    html = """
    <!DOCTYPE html>
    <html>
    <head><title>OCR Streaming</title></head>
    <body>
        <h1>OCR Streaming Demo</h1>
        <div id="output"></div>
        <script>
            const ws = new WebSocket("ws://localhost:8000/ws/ocr");
            const output = document.getElementById("output");
            
            ws.onopen = () => {
                ws.send(JSON.stringify({
                    image_path: "test.jpg",
                    prompt: "<image>\\nFree OCR."
                }));
            };
            
            ws.onmessage = (event) => {
                const data = JSON.parse(event.data);
                if (data.token) {
                    output.textContent += data.token;
                } else if (data.status) {
                    console.log("Status:", data.status);
                }
            };
        </script>
    </body>
    </html>
    """
    return HTMLResponse(html)

if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8000)
'''
    
    print("=" * 80)
    print("Example 4: WebSocket Streaming")
    print("=" * 80)
    print(code)


if __name__ == '__main__':
    print("\n" + "=" * 80)
    print("Solution 2: Custom Streamer for Token Streaming")
    print("=" * 80)
    print("\nThis solution demonstrates how to capture streaming tokens")
    print("instead of printing them to console.\n")
    
    # Run examples
    example_console_streaming()
    print("\n")
    example_callback_processing()
    print("\n")
    example_flask_sse()
    print("\n")
    example_websocket()
    
    print("\n" + "=" * 80)
    print("Note: For production use, consider Solution 3 (vLLM)")
    print("which has native async streaming support and better performance.")
    print("=" * 80)
