"""
Utility functions for converting LaTeX math delimiters to Markdown format.

This module provides functions to convert LaTeX-style math delimiters to 
Markdown-compatible math delimiters:
- Inline math: \(...\) -> $...$
- Display math: \[...\] -> $$...$$

This fixes the issue where LaTeX formulas generated by the model use \( and \)
which are not valid escape sequences and are not recognized by Markdown readers.
"""

import re


def convert_latex_to_markdown(text: str) -> str:
    """
    Convert LaTeX math delimiters to Markdown math delimiters.
    
    Converts:
    - Inline math: \(...\) -> $...$
    - Display math: \[...\] -> $$...$$
    
    Args:
        text (str): Text containing LaTeX math delimiters
        
    Returns:
        str: Text with Markdown math delimiters
        
    Examples:
        >>> convert_latex_to_markdown(r"\(A > 50\%\)")
        "$A > 50\\%$"
        >>> convert_latex_to_markdown(r"\[E = mc^2\]")
        "$$E = mc^2$$"
    """
    if not text:
        return text
    
    # Convert display math \[...\] to $$...$$
    # Use non-greedy matching to handle multiple formulas
    text = re.sub(
        r'\\\[(.*?)\\\]',
        r'$$\1$$',
        text,
        flags=re.DOTALL
    )
    
    # Convert inline math \(...\) to $...$
    # Use non-greedy matching to handle multiple formulas
    text = re.sub(
        r'\\\((.*?)\\\)',
        r'$\1$',
        text,
        flags=re.DOTALL
    )
    
    return text


def convert_latex_to_markdown_with_tags(text: str) -> str:
    """
    Convert LaTeX math delimiters to Markdown with special tags.
    
    This is an alternative approach that wraps math content with special tags
    like <|math|>...<|/math|> as suggested in the GitHub issue.
    
    Converts:
    - Inline math: \(...\) -> <|math|>$...$<|/math|>
    - Display math: \[...\] -> <|math|>$$...$$<|/math|>
    
    Args:
        text (str): Text containing LaTeX math delimiters
        
    Returns:
        str: Text with tagged Markdown math delimiters
        
    Examples:
        >>> convert_latex_to_markdown_with_tags(r"\(A > 50\%\)")
        "<|math|>$A > 50\\%$<|/math|>"
    """
    if not text:
        return text
    
    # Convert display math \[...\] to <|math|>$$...$$<|/math|>
    text = re.sub(
        r'\\\[(.*?)\\\]',
        r'<|math|>$$\1$$<|/math|>',
        text,
        flags=re.DOTALL
    )
    
    # Convert inline math \(...\) to <|math|>$...$<|/math|>
    text = re.sub(
        r'\\\((.*?)\\\)',
        r'<|math|>$\1$<|/math|>',
        text,
        flags=re.DOTALL
    )
    
    return text
